services:
  rinexpos:
    image: rinexpos
    build: .
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - OCTAVE_NO_GUI=true
      - PYTHONUNBUFFERED=1
    command: ["bash", "-c", "echo 'RINEX Processing Environment Ready! Use: docker-compose exec rinexpos python3 python/readnav.py or docker-compose exec rinexpos octave --eval \"rinexnav\"' && tail -f /dev/null"]