services:
  rinexpos:
    image: rinexpos
    build: .
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - OCTAVE_NO_GUI=true
      - PYTHONUNBUFFERED=1
    command: 
      - bash
      - -c
      - |
        echo 'RINEX Processing Environment Ready!'
        echo ''
        echo 'Python processing:'
        echo '  docker-compose exec rinexpos python3 python/rinexnav.py --file=data/chur1610.19n'
        echo ''
        echo 'MATLAB/Octave processing:'
        echo '  docker-compose exec rinexpos bash -c "cd matlab && octave rinexnav_enhanced.m"'
        echo ''
        tail -f /dev/null

  test:
    image: rinexpos-test
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./:/usr/src/app
      - ./.git:/usr/src/app/.git
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - SEMGREP_APP_TOKEN=${SEMGREP_APP_TOKEN:-}
    profiles:
      - test
    command: 
      - bash
      - -c
      - |
        echo '=============== Running Checks Tools ===============' &&
        
        black --check python/ && echo 'Black OK' &&
        
        ruff check python/ && echo 'Ruff OK' &&

        bandit -r python/ && echo 'Bandit OK' &&

        safety check && echo 'Safety OK' &&

        if [ -n "$SEMGREP_APP_TOKEN" ]; then
          git config --global --add safe.directory /usr/src/app &&
          semgrep \
            --config=p/python \
            --config=p/dockerfile \
            --config=p/ci \
            --config=p/owasp-top-ten \
            --config=p/security-audit \
            --config=p/secrets \
            --config=p/supply-chain \
            --metrics=off \
            --error \
            --no-git-ignore . && echo 'Semgrep OK'
        else
          echo 'Skipping Semgrep (no token provided)'
        fi &&

        pytest tests/ -v --tb=short --disable-warnings &&
        
        echo '=============== All Tests Completed ==============='
      # mypy python/ && echo 'MyPy OK'
      # Original Semgrep cloud upload results version
      # semgrep ci --supply-chain && echo 'Semgrep OK'