services:
  rinexpos:
    image: rinexpos
    build: .
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - OCTAVE_NO_GUI=true
      - PYTHONUNBUFFERED=1
    command: ["bash", "-c", "echo 'RINEX Processing Environment Ready! Use: docker-compose exec rinexpos python3 python/rinexnav.py --file=data/chur1610.19n  or docker-compose exec rinexpos bash -c \"cd matlab && octave rinexnav_enhanced.m\"' && tail -f /dev/null"]